In [5]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [6]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"tkingofficial","key":"21032e28550108a356c672002319a743"}'}

In [7]:
!mkdir -p /.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot create regular file '/root/.kaggle/': Not a directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [8]:
!kaggle datasets download -d sumanbera19/bengaluru-house-price-dataset

Dataset URL: https://www.kaggle.com/datasets/sumanbera19/bengaluru-house-price-dataset
License(s): CC0-1.0
Downloading bengaluru-house-price-dataset.zip to /content
100% 194k/194k [00:00<00:00, 734kB/s]

In [9]:
import zipfile

In [10]:
with zipfile.ZipFile("/content/bengaluru-house-price-dataset.zip","r") as z:
  z.extractall("HOUSE")

In [11]:
import numpy as np
import pandas as pd

In [12]:
data= pd.read_csv("/content/HOUSE/bengaluru_house_prices.csv")
df= pd.DataFrame(data)
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [14]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [15]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [16]:
df.size

119880

In [17]:
df_1 = df.dropna()

In [18]:
df_1.shape

(7496, 9)

In [19]:
df_2 = df.fillna(100)

In [20]:
df_2

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,100,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,100,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,100,3600,5.0,100.0,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,100,550,1.0,1.0,17.00

In [21]:
cat_col= df.select_dtypes(include=["object"]).columns.tolist()
cat_col

['area_type', 'availability', 'location', 'size', 'society', 'total_sqft']

In [22]:
num_col= df.select_dtypes (include=["int64", "float64"]).columns.tolist()
num_col

['bath', 'balcony', 'price']

In [23]:
df.shape

(13320, 9)

In [24]:
a=df.isnull().sum()/df.shape[0]*100
a

area_type        0.000000
availability     0.000000
location         0.007508
size             0.120120
society         41.306306
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
dtype: float64

In [25]:
b=a[a>17].keys()
b

Index(['society'], dtype='object')

In [26]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [27]:
df.drop(b, axis=1, inplace=True)
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [28]:
import time

In [29]:
df['price']=df['price']*100000
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,3907000.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,12000000.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,6200000.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,9500000.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,5100000.0
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,23100000.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,NaN,40000000.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,6000000.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,48800000.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,1700000.0

In [30]:
from sklearn.impute import SimpleImputer

In [31]:
cat_clean=SimpleImputer(strategy="most_frequent")
num_clean=SimpleImputer(strategy="mean")
cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

['area_type', 'availability', 'location', 'size', 'total_sqft']

In [32]:
df['price'].dtypes

dtype('float64')

In [34]:
df[cat_col]

,area_type,availability,location,size,total_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200
...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550

In [33]:
df['total_sqft'].dtypes

dtype('O')