In [28]:
#PROJECT 7

import pandas as pd
import numpy as np

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler

In [30]:
# STEP 2: LOAD THE CSV FILE FROM GITHUB

import io

# The user provided the raw CSV content directly as a string.
csv_data = """PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S
2,1,1,"Cumings, Mrs. John Bradley",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,,S
4,1,1,"Futrelle, Mrs. Jacques Heath",female,35,1,0,113803,53.1,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,,S
6,0,3,"Moran, Mr. James",male,,0,0,330877,8.4583,,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.075,,S
9,1,3,"Johnson, Mrs. Oscar W",female,27,0,2,347742,11.1333,,S
10,1,2,"Nasser, Mrs. Nicholas",female,14,1,0,237736,30.0708,,C
11,1,3,"Sandstrom, Miss. Marguerite",female,4,1,1,PP 9549,16.7,G6,S
12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S
13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,A/5. 2151,8.05,,S
14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.275,,S
15,0,3,"Vestrom, Miss. Hulda Amanda",female,14,0,0,350406,7.8542,,S
16,1,2,"Hewlett, Mrs. Mary D",female,55,0,0,248706,16.0,,S
17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.125,,Q
18,1,2,"Williams, Mr. Charles Eugene",male,,0,0,244373,13.0,,S
19,0,3,"Vander Planke, Mrs. Julius",female,31,1,0,345763,18.0,,S
20,1,3,"Masselmani, Mrs. Fatima",female,,0,0,2649,7.225,,C
21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26.0,,S
22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13.0,D56,S
23,1,3,"McGowan, Miss. Anna",female,15,0,0,330923,8.0292,,Q
24,0,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.5,A6,S
25,0,3,"Palsson, Miss. Torborg Danira",female,8,3,1,349909,21.075,,S
26,1,3,"Asplund, Mrs. Carl Oscar",female,38,1,5,347077,31.3875,,S
27,0,3,"Emir, Mr. Farred Chehab",male,,0,0,2631,7.225,,C
28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0,C23 C25 C27,S
29,1,3,"O'Dwyer, Miss. Ellen",female,,0,0,330959,7.8792,,Q
30,0,3,"Todoroff, Mr. Lalio",male,,0,0,349216,7.8958,,S
31,0,2,"Meyer, Mr. Edgar Joseph",male,29,0,0,248723,21.0,,S
32,1,1,"Silvey, Mrs. William Baird",female,50,1,0,13507,55.9,E44,S
33,0,3,"Madsen, Mr. Fridtjof Arne",male,24,0,0,C 17369,7.4958,,S
34,1,2,"Nye, Miss. Elizabeth",female,18,0,1,231919,23.0,,S
35,0,3,"Petroff, Mr. Pastcho",male,26,0,0,349215,7.8958,,S
36,1,1,"Astor, Mrs. John Jacob",female,18,1,0,PC 17757,227.525,B77,C
37,0,3,"Kraeff, Mr. Theodor",male,25,0,0,349253,7.925,,S
38,1,2,"Collyer, Mrs. Harvey",female,30,1,1,C.A. 31921,26.25,,S
39,0,3,"Canavan, Miss. Mary",female,,0,0,364858,7.75,,Q
40,1,1,"Harper, Mr. Henry Sleeper",male,48,1,0,PC 17572,76.7292,D33,C"""

# Read the CSV data from the string into a pandas DataFrame
df = pd.read_csv(io.StringIO(csv_data))

# Display the first 5 rows to confirm it's loaded correctly
display(df.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [31]:
print("first five rows")

display(df.head())

first five rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [32]:
print(df.shape)

(40, 12)

In [33]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  40 non-null     int64
 1   Survived     40 non-null     int64
 2   Pclass       40 non-null     int64
 3   Name         40 non-null     object
 4   Sex          40 non-null     object
 5   Age          33 non-null     float64
 6   SibSp        40 non-null     int64
 7   Parch        40 non-null     int64
 8   Ticket       40 non-null     object
 9   Fare         40 non-null     float64
 10  Cabin        11 non-null     object
 11  Embarked     40 non-null     object
dtypes: float64(2), int64(5), object(5)
memory usage: 3.9+ KB

In [35]:
df.info

<bound method DataFrame.info of     PassengerId  Survived  Pclass                            Name     Sex  \
0             1         0       3         Braund, Mr. Owen Harris    male
1             2         1       1      Cumings, Mrs. John Bradley  female
2             3         1       3          Heikkinen, Miss. Laina  female
3             4         1       1    Futrelle, Mrs. Jacques Heath  female
4             5         0       3        Allen, Mr. William Henry    male
5             6         0       3                Moran, Mr. James    male
6             7         0       1         McCarthy, Mr. Timothy J    male
7             8         0       3  Palsson, Master. Gosta Leonard    male
8             9         1       3           Johnson, Mrs. Oscar W  female
9            10         1       2           Nasser, Mrs. Nicholas  female
10           11         1       3     Sandstrom, Miss. Marguerite  female
11           12         1       1        Bonnell, Miss. Elizabeth  female
12           13         0       3  Saundercock, Mr. William Henry    male
13           14         0       3     Andersson, Mr. Anders Johan    male
14           15         0       3     Vestrom, Miss. Hulda Amanda  female
15           16         1       2            Hewlett, Mrs. Mary D  female
16           17         0       3            Rice, Master. Eugene    male
17           18         1       2    Williams, Mr. Charles Eugene    male
18           19         0       3      Vander Planke, Mrs. Julius  female
19           20         1       3         Masselmani, Mrs. Fatima  female
20           21         0       2            Fynney, Mr. Joseph J    male
21           22         1       2           Beesley, Mr. Lawrence    male
22           23         1       3             McGowan, Miss. Anna  female
23           24         0       1    Sloper, Mr. William Thompson    male
24           25         0       3   Palsson, Miss. Torborg Danira  female
25           26         1       3        Asplund, Mrs. Carl Oscar  female
26           27         0       3         Emir, Mr. Farred Chehab    male
27           28         0       1  Fortune, Mr. Charles Alexander    male
28           29         1       3            O'Dwyer, Miss. Ellen  female
29           30         0       3             Todoroff, Mr. Lalio    male
30           31         0       2         Meyer, Mr. Edgar Joseph    male
31           32         1       1      Silvey, Mrs. William Baird  female
32           33         0       3       Madsen, Mr. Fridtjof Arne    male
33           34         1       2            Nye, Miss. Elizabeth  female
34           35         0       3            Petroff, Mr. Pastcho    male
35           36         1       1          Astor, Mrs. John Jacob  female
36           37         0       3             Kraeff, Mr. Theodor    male
37           38         1       2            Collyer, Mrs. Harvey  female
38           39         0       3             Canavan, Miss. Mary  female
39           40         1       1       Harper, Mr. Henry Sleeper    male

     Age  SibSp  Parch            Ticket      Fare        Cabin Embarked
0   22.0      1      0         A/5 21171    7.2500          NaN        S
1   38.0      1      0          PC 17599   71.2833          C85        C
2   26.0      0      0  STON/O2. 3101282    7.9250          NaN        S
3   35.0      1      0            113803   53.1000         C123        S
4   35.0      0      0            373450    8.0500          NaN        S
5    NaN      0      0            330877    8.4583          NaN        Q
6   54.0      0      0             17463   51.8625          E46        S
7    2.0      3      1            349909   21.0750          NaN        S
8   27.0      0      2            347742   11.1333          NaN        S
9   14.0      1      0            237736   30.0708          NaN        C
10   4.0      1      1           PP 9549   16.7000           G6        S
11  58.0      0      0            113783   26.5500         C103        S
12  20.0      0      0         A/5. 2151    8.0500          NaN        S
13  39.0      1      5            347082   31.2750          NaN        S
14  14.0      0      0            350406    7.8542          NaN        S
15  55.0      0      0            248706   16.0000          NaN        S
16   2.0      4      1            382652   29.1250          NaN        Q
17   NaN      0      0            244373   13.0000          NaN        S
18  31.0      1      0            345763   18.0000          NaN        S
19   NaN      0      0              2649    7.2250          NaN        C
20  35.0      0      0            239865   26.0000          NaN        S
21  34.0      0      0            248698   13.0000          D56        S
22  15.0      0      0            330923    8.0292          NaN        Q
23  28.0      0      0            113788   35.5000           A6        S
24   8.0      3      1            349909   21.0750          NaN        S
25  38.0      1      5            347077   31.3875          NaN        S
26   NaN      0      0              2631    7.2250          NaN        C
27  19.0      3      2             19950  263.0000  C23 C25 C27        S
28   NaN      0      0            330959    7.8792          NaN        Q
29   NaN      0      0            349216    7.8958          NaN        S
30  29.0      0      0            248723   21.0000          NaN        S
31  50.0      1      0             13507   55.9000          E44        S
32  24.0      0      0           C 17369    7.4958          NaN        S
33  18.0      0      1            231919   23.0000          NaN        S
34  26.0      0      0            349215    7.8958          NaN        S
35  18.0      1      0          PC 17757  227.5250          B77        C
36  25.0      0      0            349253    7.9250          NaN        S
37  30.0      1      1        C.A. 31921   26.2500          NaN        S
38   NaN      0      0            364858    7.7500          NaN        Q
39  48.0      1      0          PC 17572   76.7292          D33        C  >

In [36]:
print(df.isnull().sum)

<bound method DataFrame.sum of     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0         False     False   False  False  False  False  False  False   False
1         False     False   False  False  False  False  False  False   False
2         False     False   False  False  False  False  False  False   False
3         False     False   False  False  False  False  False  False   False
4         False     False   False  False  False  False  False  False   False
5         False     False   False  False  False   True  False  False   False
6         False     False   False  False  False  False  False  False   False
7         False     False   False  False  False  False  False  False   False
8         False     False   False  False  False  False  False  False   False
9         False     False   False  False  False  False  False  False   False
10        False     False   False  False  False  False  False  False   False
11        False     False   False  False  False  False  False  False   False
12        False     False   False  False  False  False  False  False   False
13        False     False   False  False  False  False  False  False   False
14        False     False   False  False  False  False  False  False   False
15        False     False   False  False  False  False  False  False   False
16        False     False   False  False  False  False  False  False   False
17        False     False   False  False  False   True  False  False   False
18        False     False   False  False  False  False  False  False   False
19        False     False   False  False  False   True  False  False   False
20        False     False   False  False  False  False  False  False   False
21        False     False   False  False  False  False  False  False   False
22        False     False   False  False  False  False  False  False   False
23        False     False   False  False  False  False  False  False   False
24        False     False   False  False  False  False  False  False   False
25        False     False   False  False  False  False  False  False   False
26        False     False   False  False  False   True  False  False   False
27        False     False   False  False  False  False  False  False   False
28        False     False   False  False  False   True  False  False   False
29        False     False   False  False  False   True  False  False   False
30        False     False   False  False  False  False  False  False   False
31        False     False   False  False  False  False  False  False   False
32        False     False   False  False  False  False  False  False   False
33        False     False   False  False  False  False  False  False   False
34        False     False   False  False  False  False  False  False   False
35        False     False   False  False  False  False  False  False   False
36        False     False   False  False  False  False  False  False   False
37        False     False   False  False  False  False  False  False   False
38        False     False   False  False  False   True  False  False   False
39        False     False   False  False  False  False  False  False   False

     Fare  Cabin  Embarked
0   False   True     False
1   False  False     False
2   False   True     False
3   False  False     False
4   False   True     False
5   False   True     False
6   False  False     False
7   False   True     False
8   False   True     False
9   False   True     False
10  False  False     False
11  False  False     False
12  False   True     False
13  False   True     False
14  False   True     False
15  False   True     False
16  False   True     False
17  False   True     False
18  False   True     False
19  False   True     False
20  False   True     False
21  False  False     False
22  False   True     False
23  False  False     False
24  False   True     False
25  False   True     False
26  False   True     False
27  False  False     False
28  False   True     False
29  False   True     False
30  False   True     False
31  False  False     False
32  False   True     False
33  False   True     False
34  False   True     False
35  False  False     False
36  False   True     False
37  False   True     False
38  False   True     False
39  False  False     False  >

In [37]:
drop_col = ['PassengerId', 'Name', 'Ticket', 'Cabin']

existing_drop_col = [col for col in drop_col if col in df.columns]

df.drop(columns= existing_drop_col, inplace=True)

print(df.columns)

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [38]:
# STEP 9: HANDLE MISSING VALUES

# Fill missing values in Age with the median
# Median is used because it is better than mean when outliers may exist

if "Age" in df.columns:
  df["Age"] = df ["Age"].fillna(df ["Age"].median())

# Fill missing values in Embarked with the mode
# Mode means the most frequent value in that column

if "Embarked" in df.columns:
  df["Embarked"] = df ["Embarked"].fillna(df ["Embarked"]. mode ([0]))

print("\nCheck Missing values after cleaning:")
print (df.isnull().sum())

Check Missing values after cleaning:
Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [ ]:
# STEP 10: SEPARATE FEATURES (X) AND TARGET (y)
# X contains the input features used for prediction #y contains the output/target column that we want to predict 
# Here, Survived is the target column

X = df.drop(columns= ["Survived"])
y = df ["Survived"]

print("\nInput features (X) preview:")
display (X.head())

print("\nTarget variable (y) preview:")
display(y.head())

Input features (X) preview:

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

Target variable (y) preview:

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [40]:

# STEP 11: APPLY ONE-HOT ENCODING TO CATEGORICAL INPUT COLUMNS
# Machine learning models work better with numeric data
# Columns like Sex and Embarked contain text values
# So we convert them into numeric format using one-hot encoding
# We only encode columns if they exist in the dataset

categorical_cols = [col for col in ["Sex", "Embarked"] if col in X.columns]

# pd.get_dummies () creates separate binary columns for each category
#drop_first=True removes one column from each category group
# This helps avoid redundant information

X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

print("\nData after one-hot encoding:")
display (X.head())

print("\nColumns after one-hot encoding:")
print(X.columns)

Data after one-hot encoding:

   Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
0       3  22.0      1      0   7.2500      True       False        True
1       1  38.0      1      0  71.2833     False       False       False
2       3  26.0      0      0   7.9250     False       False        True
3       1  35.0      1      0  53.1000     False       False        True
4       3  35.0      0      0   8.0500      True       False        True

Columns after one-hot encoding:
Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [41]:
# step 12 :applyed label encoding to the target columns
# label encoding converts class labels into numbers
# In this dataset ,su
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
print("\nTarget variable after label encoding:")
print(y_encoded[:10])

Target variable after label encoding:
[0 1 1 1 0 0 0 0 1 1]

In [42]:

# STEP 13: SPLIT DATA INTO TRAINING AND TESTING SETS

# train_test_split divides the data into:
#- training data: used to train the model
#- testing data: used to evaluate the model

# test_size=0.2 means 20% data goes to testing, 80% to training
# random_state=42 ensures the split stays the same every time we run the code

X_train, X_test, y_train, y_test= train_test_split(
  X, y_encoded, test_size = 0.2, random_state=42
)

print("\nTrain-Test Split Shapes: ")
print("X_train:", X_train. shape)
print("X_test:", X_test.shape)
print("y_train: ", y_train. shape)
print("y_test:", y_test.shape)

Train-Test Split Shapes:
X_train: (32, 8)
X_test: (8, 8)
y_train:  (32,)
y_test: (8,)

In [45]:

# Step 14: apply standardization

# Standardization changes the data so that: #mean becomes 0
# - standard deviation becomes 1
# This is useful when features have different ranges

# Create StandardScaler object

standard_scaler= StandardScaler()

#fit_transform() is used on training data:
#fit() learns the mean and standard deviation from training data #transform() applies the scaling

X_train_standardized = standard_scaler.fit_transform(X_train)

# Only transform() is used on test data
# We do NOT fit again on test data
# This avoids data leakage

X_test_standardized = standard_scaler.transform (X_test)
print("\nFirst 5 rows after standardization:")
print(X_train_standardized [:5])

First 5 rows after standardization:
[[-1.55236467e+00  1.54015802e+00  5.93390829e-01 -4.00000000e-01
   1.16262334e+00  1.06458129e+00 -3.77964473e-01 -1.73205081e+00]
 [-1.55236467e+00  2.00148460e+00 -6.72509606e-01 -4.00000000e-01
   5.43307833e-01  1.06458129e+00 -3.77964473e-01  5.77350269e-01]
 [ 8.13143398e-01  7.71280379e-01  5.93390829e-01  3.60000000e+00
   3.33694436e-02 -9.39336437e-01 -3.77964473e-01  5.77350269e-01]
 [-3.69610635e-01 -1.07402595e+00  5.93390829e-01 -4.00000000e-01
   5.76482547e-04 -9.39336437e-01 -3.77964473e-01 -1.73205081e+00]
 [ 8.13143398e-01  8.48168143e-01  5.93390829e-01  3.60000000e+00
   3.05675843e-02  1.06458129e+00 -3.77964473e-01  5.77350269e-01]]

In [47]:

# STEP 15: APPLY NORMALIZATION

# Normalization scales the values into a fixed range, usually to 1 # This is useful when we want all features to be on the same scale
# Create MinMaxScaler object

minmax_scaler= MinMaxScaler()

# Fit and transform training data

X_train_normalized = minmax_scaler.fit_transform(X_train)

#Transform test data using the same scaler X_

test_normalized = minmax_scaler.transform(X_test)

print("\nFirst 5 rows after normalization:")
print(X_train_normalized[:5])

First 5 rows after normalization:
[[0.         0.82142857 0.33333333 0.         0.31542027 1.
  0.         0.        ]
 [0.         0.92857143 0.         0.         0.20253093 1.
  0.         1.        ]
 [1.         0.64285714 0.33333333 1.         0.10957894 0.
  0.         1.        ]
 [0.5        0.21428571 0.33333333 0.         0.10360141 0.
  0.         0.        ]
 [1.         0.66071429 0.33333333 1.         0.10906821 1.
  0.         1.        ]]

In [26]:
# STEP 16: FINAL SUMMARY

print("\nProject completed successfully!")
print("\nTopics Covered: ")
print("1. Data fetching from GitHub")
print("2. Data cleaning")
print("3. Handling missing values")
print("4. One-hot encoding")
print("5. Label encoding")
print("6. Train-test split")
print("7. Standardization")
print("8. Normalization")

Project completed successfully!

Topics Covered:
1. Data fetching from GitHub
2. Data cleaning
3. Handling missing values
4. One-hot encoding
5. Label encoding
6. Train-test split
7. Standardization
8. Normalization